blank_issues_enabled: false
contact_links:
  - name: RERC at EPA.gov
    url: https://www.epa.gov/smartgrowth/recreation-economy-rural-communities
    about: Learn about the Recreation Economy for Rural Communities program.
